# Generated by Django 6.1 on 2026-09-05 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, help_text='List known drug, food, or environmental allergies')),
                ('current_medications', models.TextField(blank=True, help_text='Ongoing medications with dosage (e.g. Metformin 500mg twice daily)')),
                ('past_conditions', models.TextField(blank=True, help_text='Chronic or past diagnoses (e.g. Type 2 Diabetes, Hypertension)')),
                ('past_surgeries', models.TextField(blank=True, help_text='Previous surgeries or hospitalizations with approximate year')),
                ('family_history', models.TextField(blank=True, help_text='Significant hereditary conditions in immediate family')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
