# Generated by Django 6.1 on 2026-09-03 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('token_number', models.PositiveIntegerField()),
                ('visit_type', models.CharField(choices=[('first_visit', 'First Visit'), ('follow_up', 'Follow-up Consultation'), ('routine_checkup', 'Routine Checkup'), ('urgent', 'Urgent / Acute Care')], default='first_visit', max_length=30)),
                ('symptom_severity', models.CharField(choices=[('mild', 'Mild (Standard examination)'), ('moderate', 'Moderate (Requires detailed diagnosis)'), ('severe', 'Severe (Complex or acute symptoms)')], default='mild', max_length=20)),
                ('has_chronic_condition', models.BooleanField(default=False)),
                ('primary_symptom', models.CharField(blank=True, max_length=255)),
                ('patient_notes', models.TextField(blank=True, help_text='Specific complaints or queries')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting in Clinic'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-Show')], default='scheduled', max_length=20)),
                ('predicted_duration_minutes', models.FloatField(default=20.0, help_text='Predicted by SmartCare ML Regressor')),
                ('actual_duration_minutes', models.FloatField(blank=True, help_text='Recorded after consultation', null=True)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_ended_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['appointment_date', 'token_number'],
                'unique_together': {('doctor', 'appointment_date', 'token_number')},
            },
        ),
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
