# Generated by Django 6.1 on 2026-09-05 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_payment'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_2h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('promoted', 'Promoted to Appointment'), ('expired', 'Expired'), ('cancelled', 'Cancelled by Patient')], default='waiting', max_length=20)),
                ('confirm_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
                ('promoted_appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_source', to='appointments.appointment')),
            ],
            options={
                'ordering': ['preferred_date', 'requested_at'],
                'unique_together': {('patient', 'doctor', 'preferred_date')},
            },
        ),
    ]
